import { DASHBOARD_I18N } from "./dashboardTranslate.js";

export const ACCOUNT_I18N = {
  en: {
    ...DASHBOARD_I18N.en,
    navAccount: "Account",
    accounts: "Accounts",
    searchAccounts: "Search account or name",
    showInactive: "Inactive",
    sort: "Sort",
    sortAccount: "Account",
    sortName: "Name",
    sortRole: "Role",
    sortLastLogin: "Last login",
    ascending: "Ascending",
    descending: "Descending",
    switchCompany: "Switch company",
    accountDetail: "Account detail",
    addAccount: "Add Account",
    editAccount: "Edit Account",
    linkAccount: "Link Account",
    currencySetting: "Currency Setting",
    accountId: "Account ID",
    name: "Name",
    role: "Role",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    passwordEditHint: "Leave blank to keep the current password",
    remark: "Remark",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    paymentAlert: "Payment Alert",
    alertType: "Alert Type",
    startDate: "Start Date",
    alertAmount: "Alert Amount",
    weekly: "Weekly",
    monthly: "Monthly",
    days: "{n} Days",
    lastLogin: "Last Login",
    currencies: "Currencies",
    currencyMatchHint: "Select one or more currencies. Only accounts that hold every selected currency stay lit.",
    pleaseSelectCurrencyFirst: "Select a currency first.",
    pleaseSelectAccountFirst: "Toggle at least one account, or leave the matching accounts unchanged.",
    assignCompanies: "Companies",
    selectRole: "Select role",
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    link: "Link",
    delete: "Delete",
    deleteConfirm: "Delete this inactive account? This cannot be undone.",
    deleteSuccess: "Account deleted",
    deleteError: "Failed to delete account",
    newCurrency: "New currency code",
    createCurrency: "Create currency",
    deleteCurrencyConfirm: "Delete currency {code}?",
    apply: "Apply",
    selectAll: "Select all",
    selectedCount: "{count} selected",
    bidirectional: "Bidirectional",
    unidirectional: "Unidirectional",
    noAccounts: "No accounts found",
    loadingAccounts: "Loading accounts...",
    loadError: "Failed to load accounts",
    detailError: "Failed to load account detail",
    saveError: "Failed to save account",
    saveSuccess: "Account saved",
    toggleError: "Failed to update account",
    linkError: "Failed to save account links",
    linkSuccess: "Account links saved",
    currencyError: "Failed to save currency settings",
    currencySuccess: "Currency settings saved",
    readOnly: "Read-only account: changes are not allowed.",
    requiredFields: "Account ID, name, role and password are required.",
    editRequiredFields: "Name and role are required.",
    alertRequired: "Alert type and start date are required when Payment Alert is enabled.",
    tapForDetail: "Tap for account detail",
    groupCompanyHint: "Choose a group, then choose a company.",
    allScopeHint: "Show accounts in the selected scope.",
    refresh: "Refresh",
  },
  zh: {
    ...DASHBOARD_I18N.zh,
    navAccount: "账户",
    accounts: "账户",
    searchAccounts: "搜索账户或名称",
    showInactive: "非活跃",
    sort: "排序",
    sortAccount: "账户",
    sortName: "名称",
    sortRole: "角色",
    sortLastLogin: "最后登录",
    ascending: "升序",
    descending: "降序",
    switchCompany: "切换公司",
    accountDetail: "账户详情",
    addAccount: "新增账户",
    editAccount: "编辑账户",
    linkAccount: "关联账户",
    currencySetting: "货币设置",
    accountId: "账户 ID",
    name: "名称",
    role: "角色",
    password: "密码",
    showPassword: "显示密码",
    hidePassword: "隐藏密码",
    passwordEditHint: "留空则保留当前密码",
    remark: "备注",
    status: "状态",
    active: "活跃",
    inactive: "非活跃",
    paymentAlert: "支付提醒",
    alertType: "提醒类型",
    startDate: "开始日期",
    alertAmount: "提醒金额",
    weekly: "每周",
    monthly: "每月",
    days: "{n} 天",
    lastLogin: "最后登录",
    currencies: "货币",
    currencyMatchHint: "可多选货币。只有同时持有所选全部货币的账户会亮起。",
    pleaseSelectCurrencyFirst: "请先选择货币。",
    pleaseSelectAccountFirst: "请勾选或取消至少一个账户。",
    assignCompanies: "所属公司",
    selectRole: "选择角色",
    save: "保存",
    saving: "保存中...",
    cancel: "取消",
    close: "关闭",
    edit: "编辑",
    link: "关联",
    delete: "删除",
    deleteConfirm: "确定删除这个非活跃账户？此操作无法撤销。",
    deleteSuccess: "账户已删除",
    deleteError: "账户删除失败",
    newCurrency: "新货币代码",
    createCurrency: "新增货币",
    deleteCurrencyConfirm: "确定删除货币 {code}？",
    apply: "应用",
    selectAll: "全选",
    selectedCount: "已选 {count} 个",
    bidirectional: "双向",
    unidirectional: "单向",
    noAccounts: "未找到账户",
    loadingAccounts: "正在加载账户...",
    loadError: "账户加载失败",
    detailError: "账户详情加载失败",
    saveError: "账户保存失败",
    saveSuccess: "账户已保存",
    toggleError: "账户更新失败",
    linkError: "账户关联保存失败",
    linkSuccess: "账户关联已保存",
    currencyError: "货币设置保存失败",
    currencySuccess: "货币设置已保存",
    readOnly: "只读账户不能进行修改。",
    requiredFields: "账户 ID、名称、角色和密码为必填项。",
    editRequiredFields: "名称和角色为必填项。",
    alertRequired: "启用支付提醒时必须填写提醒类型和开始日期。",
    tapForDetail: "点击查看账户详情",
    groupCompanyHint: "先选择 Group，再选择公司。",
    allScopeHint: "显示所选范围内的账户。",
    refresh: "刷新",
  },
};

export function accountText(lang) {
  return ACCOUNT_I18N[lang === "zh" ? "zh" : "en"];
}
