import { DASHBOARD_I18N } from "./dashboardTranslate.js";

export const ADMIN_I18N = {
  en: {
    ...DASHBOARD_I18N.en,
    users: "User Management",
    usersSubtitle: "Users, roles and permissions",
    searchUsers: "Search Login ID, name or email",
    showInactive: "Inactive",
    switchCompany: "Switch company",
    allScopeHint: "Show users in the selected scope.",
    userDetail: "User detail",
    addUser: "Add User",
    editUser: "Edit User",
    loginId: "Login ID",
    name: "Name",
    email: "Email",
    role: "Role",
    status: "Status",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    passwordEditHint: "Leave blank to keep the current password",
    active: "Active",
    inactive: "Inactive",
    lastLogin: "Last Login",
    createdBy: "Created By",
    selectRole: "Select role",
    basicInfo: "Basic Information",
    belonging: "Group / Company",
    selectGroupCompany: "Select Group / Company",
    searchGroupCompany: "Filter by Group or Company",
    groupsSection: "Groups",
    companiesSection: "Companies",
    noGroups: "No groups found",
    noCompanies: "No companies found",
    noneSelected: "None selected",
    pagePermissions: "Page Permissions",
    dataPermissions: "Data Permissions",
    accountPermissions: "Account Permissions",
    processPermissions: "Process Permissions",
    selectedCount: "{count} selected",
    selectAll: "Select all",
    clearAll: "Clear all",
    searchOptions: "Search",
    readOnlyToggle: "Read Only",
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    done: "Done",
    apply: "Apply",
    deleteConfirm: "Delete this user? This cannot be undone.",
    deleteInactiveOnly: "Only inactive users can be deleted.",
    deleteSuccess: "User deleted",
    deleteError: "Failed to delete user",
    statusUpdated: "Status updated",
    toggleError: "Failed to update status",
    loadingUsers: "Loading users...",
    noUsers: "No users found",
    loadError: "Failed to load users",
    detailError: "Failed to load user detail",
    saveError: "Failed to save user",
    saveSuccess: "User saved",
    readOnly: "Read-only account: changes are not allowed.",
    requiredFields: "Login ID, name, email, role and password are required.",
    editRequiredFields: "Name, email and role are required.",
    invalidEmail: "Invalid email format.",
    singleCompanyRequired: "Select a single company to add or modify users.",
    ownerShadowHint: "Owner profile: only name, email and password can be changed.",
    discardConfirm: "Discard unsaved changes?",
    tapForDetail: "Tap for user detail",
    permHome: "Home",
    permAdmin: "Admin",
    permAccount: "Account",
    permOwnership: "Ownership",
    permProcess: "Process",
    permDatacapture: "Data Capture",
    permPayment: "Transaction Payment",
    permReport: "Report",
    permMaintenance: "Maintenance",
  },
  zh: {
    ...DASHBOARD_I18N.zh,
    users: "用户管理",
    usersSubtitle: "用户、角色与权限",
    searchUsers: "搜索 Login ID、名称或邮箱",
    showInactive: "非活跃",
    switchCompany: "切换公司",
    allScopeHint: "显示所选范围内的用户。",
    userDetail: "用户详情",
    addUser: "新增用户",
    editUser: "编辑用户",
    loginId: "Login ID",
    name: "名称",
    email: "邮箱",
    role: "角色",
    status: "状态",
    password: "密码",
    showPassword: "显示密码",
    hidePassword: "隐藏密码",
    passwordEditHint: "留空则保留当前密码",
    active: "活跃",
    inactive: "非活跃",
    lastLogin: "最后登录",
    createdBy: "创建人",
    selectRole: "选择角色",
    basicInfo: "基本资料",
    belonging: "Group / 公司",
    selectGroupCompany: "选择 Group / 公司",
    searchGroupCompany: "搜索 Group 或公司",
    groupsSection: "Groups",
    companiesSection: "公司",
    noGroups: "没有找到 Group",
    noCompanies: "没有找到公司",
    noneSelected: "未选择",
    pagePermissions: "页面权限",
    dataPermissions: "数据权限",
    accountPermissions: "Account 权限",
    processPermissions: "Process 权限",
    selectedCount: "已选 {count} 项",
    selectAll: "全选",
    clearAll: "清空",
    searchOptions: "搜索",
    readOnlyToggle: "只读",
    save: "保存",
    saving: "保存中...",
    cancel: "取消",
    edit: "编辑",
    delete: "删除",
    done: "完成",
    apply: "应用",
    deleteConfirm: "确认删除此用户？该操作不可撤销。",
    deleteInactiveOnly: "只能删除非活跃用户。",
    deleteSuccess: "用户已删除",
    deleteError: "删除用户失败",
    statusUpdated: "状态已更新",
    toggleError: "更新状态失败",
    loadingUsers: "加载用户中...",
    noUsers: "没有找到用户",
    loadError: "加载用户失败",
    detailError: "加载用户详情失败",
    saveError: "保存用户失败",
    saveSuccess: "用户已保存",
    readOnly: "只读账户：不允许修改。",
    requiredFields: "Login ID、名称、邮箱、角色和密码为必填。",
    editRequiredFields: "名称、邮箱和角色为必填。",
    invalidEmail: "邮箱格式不正确。",
    singleCompanyRequired: "请选择单个公司后再新增或修改用户。",
    ownerShadowHint: "Owner 资料：仅可修改名称、邮箱和密码。",
    discardConfirm: "放弃未保存的更改？",
    tapForDetail: "点按查看用户详情",
    permHome: "首页",
    permAdmin: "管理",
    permAccount: "账户",
    permOwnership: "所有权",
    permProcess: "流程",
    permDatacapture: "数据录入",
    permPayment: "交易支付",
    permReport: "报表",
    permMaintenance: "维护",
  },
};

export function adminText(lang) {
  return ADMIN_I18N[lang] || ADMIN_I18N.en;
}
