import { DASHBOARD_I18N } from "./dashboardTranslate.js";
import { createGetText } from "./i18nHelpers.js";

export const ANNOUNCEMENT_I18N = {
  en: {
    ...DASHBOARD_I18N.en,
    pageTitle: "Announcement",
    pageSubtitle: "Publish and manage C168 announcements & maintenance.",
    announcementDescription: "Create, edit and delete announcements.",
    backToMore: "Back to More",
    announcementTab: "Announcement",
    maintenanceTab: "Maintenance",
    publishedAnnouncements: "Published Announcements",
    noAnnouncements: "No announcements",
    createNewAnnouncement: "New Announcement",
    editAnnouncement: "Edit Announcement",
    titleRequired: "Title *",
    enterAnnouncementTitle: "Enter announcement title",
    sectionLabelOptional: "List section title (optional)",
    enterSectionLabel: "e.g. ✨ This update includes ✨",
    sectionLabelHint: "Shown above the numbered list on the notification card. Leave empty to use the default.",
    contentRequired: "Content *",
    enterAnnouncementContent: "Enter announcement content",
    publishAnnouncement: "Publish Announcement",
    publishing: "Publishing…",
    saveChanges: "Save Changes",
    saving: "Saving…",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    confirm: "Confirm",
    confirmTitle: "Confirm",
    close: "Close",
    createdBy: "CREATED BY: {name}",
    createdAt: "CREATED AT: {time}",
    confirmDeleteAnnouncement: 'Delete announcement "{title}"? This cannot be undone.',
    announcementPublishedSuccess: "Announcement published successfully",
    announcementUpdatedSuccess: "Announcement updated successfully",
    announcementDeletedSuccess: "Announcement deleted successfully",
    loadAnnouncementsFailed: "Failed to load announcements: {message}",
    loadMaintenanceFailed: "Failed to load maintenance content: {message}",
    publishFailed: "Publish failed: {message}",
    updateFailed: "Update failed: {message}",
    deleteFailed: "Delete failed: {message}",
    failedToDelete: "Failed to delete: {message}",
    titleCannotBeEmpty: "Title cannot be empty",
    prefixCannotBeEmpty: "Prefix cannot be empty",
    contentCannotBeEmpty: "Content cannot be empty",
    accessDenied: "Announcement is only available on company C168.",
    loading: "Loading…",
    createNewMaintenanceContent: "New Maintenance Content",
    editMaintenanceContent: "Edit Maintenance Content",
    prefixRequired: "Prefix *",
    enterMaintenancePrefix: "e.g. System Maintenance:",
    enterMaintenanceContent: "Enter maintenance content",
    publishMaintenanceContent: "Publish Maintenance Content",
    publishedMaintenanceContent: "Published Maintenance Content",
    noMaintenanceContent: "No maintenance content",
    noticeLabel: "Notice",
    maintenanceNotice: "Maintenance content already exists. Delete it before creating a new one.",
    confirmDeleteMaintenance: "Delete this maintenance content? This cannot be undone.",
    maintenancePublishedSuccess: "Maintenance content published successfully",
    maintenanceUpdatedSuccess: "Maintenance content updated successfully",
    maintenanceDeletedSuccess: "Maintenance content deleted successfully",
    modeStatusLabel: "Maintenance Mode",
    modeHint: "Only IT allowlist users can access while enabled.",
    modeEnableNeedsMaintenance: "Please publish maintenance content before enabling maintenance mode.",
    modeEnabledSuccess: "Maintenance mode enabled",
    modeDisabledSuccess: "Maintenance mode disabled",
    modeToggleFailed: "Maintenance mode update failed: {message}",
    modeApplying: "Applying…",
  },
  zh: {
    ...DASHBOARD_I18N.zh,
    pageTitle: "公告",
    pageSubtitle: "发布与管理 C168 公告与维护内容。",
    announcementDescription: "创建、编辑与删除公告。",
    backToMore: "返回更多",
    announcementTab: "公告",
    maintenanceTab: "维护",
    publishedAnnouncements: "已发布公告",
    noAnnouncements: "暂无公告",
    createNewAnnouncement: "新建公告",
    editAnnouncement: "编辑公告",
    titleRequired: "标题 *",
    enterAnnouncementTitle: "请输入公告标题",
    sectionLabelOptional: "列表分区标题（可选）",
    enterSectionLabel: "例如：✨ 本次更新包括 ✨",
    sectionLabelHint: "显示在铃铛通知卡编号列表上方；留空则用默认「本次更新包括」。",
    contentRequired: "内容 *",
    enterAnnouncementContent: "请输入公告内容",
    publishAnnouncement: "发布公告",
    publishing: "发布中…",
    saveChanges: "保存更改",
    saving: "保存中…",
    edit: "编辑",
    delete: "删除",
    cancel: "取消",
    confirm: "确认",
    confirmTitle: "确认",
    close: "关闭",
    createdBy: "创建者：{name}",
    createdAt: "创建时间：{time}",
    confirmDeleteAnnouncement: "确定要删除公告“{title}”吗？此操作不可撤销。",
    announcementPublishedSuccess: "公告发布成功",
    announcementUpdatedSuccess: "公告更新成功",
    announcementDeletedSuccess: "公告删除成功",
    loadAnnouncementsFailed: "加载公告失败：{message}",
    loadMaintenanceFailed: "加载维护内容失败：{message}",
    publishFailed: "发布失败：{message}",
    updateFailed: "更新失败：{message}",
    deleteFailed: "删除失败：{message}",
    failedToDelete: "删除失败：{message}",
    titleCannotBeEmpty: "标题不能为空",
    prefixCannotBeEmpty: "前缀不能为空",
    contentCannotBeEmpty: "内容不能为空",
    accessDenied: "公告管理仅在 C168 公司下可用。",
    loading: "加载中…",
    createNewMaintenanceContent: "新建维护内容",
    editMaintenanceContent: "编辑维护内容",
    prefixRequired: "前缀 *",
    enterMaintenancePrefix: "例如：系统维护中:",
    enterMaintenanceContent: "请输入维护内容",
    publishMaintenanceContent: "发布维护内容",
    publishedMaintenanceContent: "已发布维护内容",
    noMaintenanceContent: "暂无维护内容",
    noticeLabel: "提示",
    maintenanceNotice: "维护内容已存在，请先删除现有内容后再创建。",
    confirmDeleteMaintenance: "确定要删除此维护内容吗？此操作不可撤销。",
    maintenancePublishedSuccess: "维护内容发布成功",
    maintenanceUpdatedSuccess: "维护内容更新成功",
    maintenanceDeletedSuccess: "维护内容删除成功",
    modeStatusLabel: "维护模式",
    modeHint: "开启后仅 IT 白名单用户可访问。",
    modeEnableNeedsMaintenance: "请先发布维护内容，再开启维护模式。",
    modeEnabledSuccess: "维护模式已开启",
    modeDisabledSuccess: "维护模式已关闭",
    modeToggleFailed: "维护模式更新失败：{message}",
    modeApplying: "处理中…",
  },
};

export const getAnnouncementText = createGetText(ANNOUNCEMENT_I18N);

export function announcementText(lang) {
  return ANNOUNCEMENT_I18N[lang === "zh" ? "zh" : "en"];
}
