import { DASHBOARD_I18N } from "./dashboardTranslate.js";
import { createGetText } from "./i18nHelpers.js";

export const AUTO_RENEW_I18N = {
  en: {
    ...DASHBOARD_I18N.en,
    pageTitle: "Auto Renew",
    pageSubtitle: "Approve renewals for companies and groups expiring within 30 days.",
    autoRenewDescription: "Approve company and group renewals.",
    backToMore: "Back to More",
    companyTab: "Company",
    groupTab: "Group",
    filterPending: "Pending",
    filterApproved: "Approved",
    filterRejected: "Rejected",
    searchPlaceholder: "Search company or name…",
    loading: "Loading…",
    accessDenied: "You do not have access to Auto Renew.",
    loadFailed: "Failed to load: {message}",
    readOnlyNotice: "Only C168 Owner or Admin can approve or reject renewals.",
    emptyTitle: "All clear for now",
    emptyHintPending: "No companies are within the 30-day renewal window, or all requests have been processed.",
    emptyHintApproved: "No approved renewals in recent history.",
    emptyHintRejected: "No rejected renewals in recent history.",
    noResults: "No renewal requests match your search or filters.",
    expirationDate: "Expiration",
    timeRemaining: "Remaining",
    renewalPeriod: "Renewal Period",
    selectPeriod: "Select period…",
    period7days: "7 days",
    period1month: "1 month",
    period3months: "3 months",
    period6months: "6 months",
    period1year: "1 year",
    colPrice: "Price",
    selectFromAccount: "From account",
    selectToAccount: "To account",
    approve: "Approve",
    reject: "Reject",
    delete: "Delete",
    cancel: "Cancel",
    confirm: "Confirm",
    confirmTitle: "Confirm",
    confirmApproveTitle: "Confirm Approve",
    confirmRejectTitle: "Confirm Reject",
    confirmDeleteTitle: "Confirm Delete",
    confirmRevertTitle: "Confirm Revert",
    processing: "Processing…",
    confirmApprove: "Approve renewal for {company}? This will extend expiration and create a payment.",
    confirmReject: "Reject renewal for {company}?",
    confirmDelete: "Delete approved renewal for {company}? Payment will be removed and expiration reverted.",
    confirmRevert: "Delete rejected renewal for {company}? Request will return to pending.",
    approvedSuccess: "Renewal approved",
    rejectedSuccess: "Renewal rejected",
    deletedSuccess: "Renewal deleted — payment removed and request returned to pending",
    revertedSuccess: "Rejected renewal deleted — request returned to pending",
    approveFailed: "Approve failed: {message}",
    rejectFailed: "Reject failed: {message}",
    deleteFailed: "Delete failed: {message}",
    noPriceHint: "Set Domain renewal price first",
    accountsNotResolved: "Customer account not linked in C168",
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",
    notSet: "Not set",
    noExpirationDate: "No expiration date",
    expExpired: "Expired",
    expToday: "Expires today",
    expDaysLeft: "{days} days left",
    detailTitle: "Renew — {company}",
    openDetail: "Open renewal",
  },
  zh: {
    ...DASHBOARD_I18N.zh,
    pageTitle: "自动续费",
    pageSubtitle: "审批 30 天内到期的客户公司与分组续费。",
    autoRenewDescription: "审批公司与集团续费申请。",
    backToMore: "返回更多",
    companyTab: "公司",
    groupTab: "集团",
    filterPending: "待审批",
    filterApproved: "已批准",
    filterRejected: "已拒绝",
    searchPlaceholder: "搜索公司或名称…",
    loading: "加载中…",
    accessDenied: "您无权访问自动续费。",
    loadFailed: "加载失败：{message}",
    readOnlyNotice: "仅 C168 Owner 或 Admin 可审批续费。",
    emptyTitle: "目前没有待处理项",
    emptyHintPending: "暂无进入 30 天续费窗口的公司，或相关请求已全部处理。",
    emptyHintApproved: "近期没有已批准的续费记录。",
    emptyHintRejected: "近期没有已拒绝的续费记录。",
    noResults: "没有符合搜索或筛选条件的续费请求。",
    expirationDate: "到期日",
    timeRemaining: "剩余时间",
    renewalPeriod: "续费周期",
    selectPeriod: "请选择周期…",
    period7days: "7 天",
    period1month: "1 个月",
    period3months: "3 个月",
    period6months: "6 个月",
    period1year: "1 年",
    colPrice: "续费金额",
    selectFromAccount: "付款账户",
    selectToAccount: "收款账户",
    approve: "批准",
    reject: "拒绝",
    delete: "删除",
    cancel: "取消",
    confirm: "确认",
    confirmTitle: "确认",
    confirmApproveTitle: "确认批准",
    confirmRejectTitle: "确认拒绝",
    confirmDeleteTitle: "确认删除",
    confirmRevertTitle: "确认回退",
    processing: "处理中…",
    confirmApprove: "确认批准 {company} 的续费？将延长到期日并创建付款。",
    confirmReject: "确认拒绝 {company} 的续费？",
    confirmDelete: "删除 {company} 的已批准续费？将删除付款并回退到期日。",
    confirmRevert: "删除 {company} 的已拒绝续费？请求将回到待审批。",
    approvedSuccess: "续费已批准",
    rejectedSuccess: "续费已拒绝",
    deletedSuccess: "已删除续费 — 付款已移除，请求回到待审批",
    revertedSuccess: "已删除拒绝记录 — 请求回到待审批",
    approveFailed: "批准失败：{message}",
    rejectFailed: "拒绝失败：{message}",
    deleteFailed: "删除失败：{message}",
    noPriceHint: "请先在 Domain 设置续费价格",
    accountsNotResolved: "未找到客户在 C168 的关联账户",
    statusPending: "待审批",
    statusApproved: "已批准",
    statusRejected: "已拒绝",
    notSet: "未设置",
    noExpirationDate: "尚未设置到期日",
    expExpired: "已过期",
    expToday: "今日到期",
    expDaysLeft: "剩余 {days} 天",
    detailTitle: "续费 — {company}",
    openDetail: "打开续费详情",
  },
};

export const getAutoRenewText = createGetText(AUTO_RENEW_I18N);

export function autoRenewText(lang) {
  return AUTO_RENEW_I18N[lang === "zh" ? "zh" : "en"];
}
