export const DASHBOARD_I18N = {
  en: {
    dashboard: "Dashboard",
    greeting: "Hello, {name}",
    dateRange: "Date Range",
    selectDateRange: "Select date range",
    filter: "Filter",
    quickSelect: "Quick Select",
    reset: "Reset",
    applyFilter: "Apply Filter",
    groupId: "Group ID",
    company: "Company",
    currency: "Currency",
    all: "All",
    period: "Period",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    thisYear: "This Year",
    earnings: "Earnings",
    profit: "Profit",
    expenses: "Expenses",
    netProfit: "Net Profit",
    netProfitChart: "Net Profit",
    thanLastMonth: "than last month",
    vsLastMonth: "vs last month",
    vsYesterday: "vs yesterday",
    vsLastWeek: "vs last week",
    vsLastYear: "vs last year",
    vsPreviousPeriod: "vs previous period",
    overview: "Overview",
    swipe: "Swipe",
    trendChart: "Trend Chart",
    statistics: "Statistics",
    currencyDistribution: "Currency Distribution",
    currencies: "Currencies",
    rate: "Rate",
    shareOfTotal: "Share of total",
    breakdownCurrency: "Currency",
    breakdownAmount: "Amount",
    breakdownOriginalAmount: "Original Amount",
    breakdownRate: "Exchange Rate",
    currencyBreakdown: "Currency breakdown",
    multiCurrencyNote: "Includes multi-currency conversion",
    ratesUnavailable: "Exchange rates unavailable — totals may be incomplete",
    loading: "Loading...",
    loadError: "Failed to load dashboard",
    noData: "No data for this period",
    logout: "Logout",
    navHome: "Home",
    navReport: "Report",
    navTransaction: "Transaction",
    navAccount: "Account",
    navMore: "More",
    to: "to",
    openMenu: "Open menu",
    closeMenu: "Close",
    dismissMenu: "Dismiss menu",
    menu: "Menu",
    notifications: "Notifications",
    noNotifications: "No notifications",
    announcements: "Announcements",
    loadingAnnouncements: "Loading announcements...",
    noAnnouncements: "No announcements",
    updateIncludes: "This update includes",
    versionUpdated: "System updated to {version}",
    announcementTeam: "EAZY COUNT TEAM",
    viewingCompany: "Viewing company",
    switchCompany: "Switch",
    language: "Language",
    from: "From",
    toDate: "To",
    customRange: "Custom",
    daysCount: "{n} days",
    rangePickHint: "Tap a start date, then an end date",
    done: "Done",
    clear: "Clear",
    viewThisYear: "View this year",
    refresh: "Refresh",
    pullToRefresh: "Pull to refresh",
    releaseToRefresh: "Release to refresh",
    groupHint: "Tap a group for group-only · Company All aggregates companies",
    retry: "Retry",
    emptyTitle: "No data for this period",
    emptyHint: "Try another date range, or switch company / group in Filter.",
    emptyErrorTitle: "Can't load this view",
    emptyErrorHint: "You may not have access, or the server failed. Retry or pick a company.",
    chartSelectSeries: "Tap a series above to show the chart",
    chartTapHint: "Tap the chart for details",
    chartTapMonthHint: "Tap a month for details",
    groupIdShort: "Group",
    allGroups: "All Groups",
  },
  zh: {
    dashboard: "仪表盘",
    greeting: "你好，{name}",
    dateRange: "日期范围",
    selectDateRange: "选择日期范围",
    filter: "筛选",
    quickSelect: "快速选择",
    reset: "重置",
    applyFilter: "应用筛选",
    groupId: "Group ID",
    company: "公司",
    currency: "币种",
    all: "全部",
    period: "周期",
    today: "今天",
    yesterday: "昨天",
    thisWeek: "本周",
    lastWeek: "上周",
    thisMonth: "本月",
    lastMonth: "上月",
    thisYear: "今年",
    earnings: "收益",
    profit: "利润",
    expenses: "支出",
    netProfit: "净利润",
    netProfitChart: "净利润",
    thanLastMonth: "较上月同期",
    vsLastMonth: "对比上月",
    vsYesterday: "对比昨天",
    vsLastWeek: "对比上周",
    vsLastYear: "对比去年",
    vsPreviousPeriod: "对比上期",
    overview: "概览",
    swipe: "滑动",
    trendChart: "趋势图",
    statistics: "统计",
    currencyDistribution: "币种分布",
    currencies: "币种",
    rate: "汇率",
    shareOfTotal: "占比",
    breakdownCurrency: "币种",
    breakdownAmount: "金额",
    breakdownOriginalAmount: "原币金额",
    breakdownRate: "汇率",
    currencyBreakdown: "币种明细",
    multiCurrencyNote: "含多币种换算",
    ratesUnavailable: "汇率暂不可用，汇总可能不完整",
    loading: "加载中...",
    loadError: "仪表盘加载失败",
    noData: "该周期暂无数据",
    logout: "退出",
    navHome: "首页",
    navReport: "报表",
    navTransaction: "交易",
    navAccount: "账户",
    navMore: "更多",
    to: "至",
    openMenu: "打开菜单",
    closeMenu: "关闭",
    dismissMenu: "关闭菜单",
    menu: "菜单",
    notifications: "通知",
    noNotifications: "暂无通知",
    announcements: "公告",
    loadingAnnouncements: "加载公告中...",
    noAnnouncements: "暂无公告",
    updateIncludes: "本次更新包括",
    versionUpdated: "系统已更新至 {version}",
    announcementTeam: "EAZY COUNT 团队",
    viewingCompany: "当前公司",
    switchCompany: "切换",
    language: "语言",
    from: "开始",
    toDate: "结束",
    customRange: "自定义",
    daysCount: "{n} 天",
    rangePickHint: "先点开始日期，再点结束日期",
    done: "完成",
    clear: "清除",
    viewThisYear: "查看今年",
    refresh: "刷新",
    pullToRefresh: "下拉刷新",
    releaseToRefresh: "松开刷新",
    groupHint: "点 Group 仅看该组 · 公司 All 汇总组内公司",
    retry: "重试",
    emptyTitle: "该周期暂无数据",
    emptyHint: "可换日期范围，或在筛选里切换公司 / Group。",
    emptyErrorTitle: "无法加载此视图",
    emptyErrorHint: "可能没有权限，或服务暂时失败。请重试或改选公司。",
    chartSelectSeries: "点上方系列以显示图表",
    chartTapHint: "点图表查看明细",
    chartTapMonthHint: "点某个月查看明细",
    groupIdShort: "Group",
    allGroups: "全部 Group",
  },
};

export function dashboardLabel(i18n, key) {
  const map = {
    today: i18n.today,
    yesterday: i18n.yesterday,
    thisWeek: i18n.thisWeek,
    lastWeek: i18n.lastWeek,
    thisMonth: i18n.thisMonth,
    lastMonth: i18n.lastMonth,
    thisYear: i18n.thisYear,
  };
  return map[key] || key;
}
