import { DASHBOARD_I18N } from "./dashboardTranslate.js";
import { createGetText } from "./i18nHelpers.js";

/** Mobile Maintenance (Transaction + Payment) dictionary. Spreads dashboard nav labels for MobileShell. */
export const MAINTENANCE_I18N = {
  en: {
    ...DASHBOARD_I18N.en,

    // More entry
    maintenance: "Maintenance",
    maintenanceDescription: "Transaction and payment records.",
    maintenanceBadge: "MAINTENANCE",

    // Hub
    hubTitle: "Maintenance Centre",
    hubSubtitle: "Review operational records and manage data.",
    backToHub: "Back to maintenance",
    backToMore: "Back to More",
    sectionRecords: "Records",
    sectionSetup: "Setup",
    comingSoon: "Coming soon",

    txMaintenanceTitle: "Transaction Maintenance",
    txMaintenanceDesc: "Review transaction and data capture records.",
    txFeatures: "Audit records · Read only · Filters",

    payMaintenanceTitle: "Payment Maintenance",
    payMaintenanceDesc: "Review and remove payment records.",
    payFeatures: "Payment history · Deleted records",
    deleteAccess: "Delete access",

    bpMaintenanceTitle: "Bank Maintenance",
    bpMaintenanceDesc: "Review and remove bank-process transactions.",
    bpFeatures: "Bank process posts · Batch select · Delete",
    bpSearchPlaceholder: "Process, account, bank or owner…",
    bpNeedCompany: "Pick a Bank company to load records.",
    bpScopeNote: "Company scope only. Same Post/Resend batch selects together.",
    bpDeleteConfirmTitle: "Delete {n} bank-process record(s)?",
    bpDeleteConfirmBody:
      "Deleted records stay visible in history. Only bank-process-sourced transactions are removed.",

    setupDataCapture: "Data Capture",
    setupFormula: "Formula",
    setupBank: "Bank Process",
    setupBankDesc: "Bank process list, filters, status and forms.",
    setupBankFeatures: "List · Status · Due · Add/Edit",
    bankProcessTitle: "Bank Process",
    bankSearchPlaceholder: "Supplier, bank, owner…",
    bankStatus: "Status",
    bankShowActive: "Active",
    bankShowInactive: "Inactive",
    bankShowOfficial: "Official",
    bankShowEInvoice: "E-Invoice",
    bankShowBlocked: "Blocked",
    bankStatusActive: "ACTIVE",
    bankStatusInactive: "INACTIVE",
    bankStatusOfficial: "OFFICIAL",
    bankStatusEInvoice: "E-INVOICE",
    bankStatusBlock: "BLOCK",
    bankAllCurrencies: "ALL",
    bankCost: "Cost",
    bankPrice: "Price",
    bankProfit: "Profit",
    bankNeedCompany: "Pick a Bank company to load processes.",
    bankUnauthorizedCompany: "This company has no Bank category. Switch company in Filter.",
    bankReadOnlyNote: "Company scope only. Use + to add, or Edit from a process card.",
    bankActionsTitle: "Process",
    bankSaveStatus: "Save status",
    bankRemark: "Remark",
    bankRemarkPlaceholder: "Add a remark…",
    bankResend: "Resend",
    bankResendTitle: "Resend to Accounting Due",
    bankProcessLabel: "Process",
    bankDayStart: "Day start",
    bankDayEnd: "Day end",
    bankFrequency: "Frequency",
    bankFreqFirstOfMonth: "1st of month",
    bankFreqMonthly: "Monthly",
    bankFreqWeek: "Weekly",
    bankFreqDay: "Daily",
    bankFreqOnce: "Once",
    bankAccountingDue: "Accounting Due",
    bankPostTransaction: "Post",
    bankPost: "Post",
    bankRefresh: "Refresh",
    bankRestoreDismissed: "Restore",
    bankNoDue: "No accounting due items.",
    bankPostedToday: "Posted today",
    bankDueAwaiting: "{n} awaiting",
    bankContract: "Contract",
    bankCustomer: "Customer",
    bankStatusUpdated: "Status updated",
    bankStatusFailed: "Failed to update status",
    bankRemarkUpdated: "Remark updated",
    bankRemarkFailed: "Failed to update remark",
    bankResendOk: "Resent to Accounting Due",
    bankResendFailed: "Resend failed",
    bankPostOk: "Posted to transaction",
    bankPostFailed: "Post failed",
    bankDismissOk: "Removed from Due",
    bankDismissFailed: "Remove failed",
    bankAddTitle: "Add process",
    bankEditTitle: "Edit process",
    bankEdit: "Edit",
    bankAdd: "Add process",
    bankFormStepIdentity: "Identity",
    bankFormStepMoney: "Money",
    bankFormStepSchedule: "Schedule",
    bankFormBack: "Back",
    bankFormNext: "Next",
    bankSectionBankInfo: "Bank information",
    bankSectionDetail: "Detail",
    bankSectionSchedule: "Schedule",
    bankSectionNotes: "Notes",
    bankCountryCurrency: "Country (Currency)",
    bankBank: "Bank",
    bankType: "Type",
    bankType_PERSONAL: "Personal",
    bankType_ENTERPRISE: "Enterprise",
    bankType_BUSINESS: "Business",
    bankCardOwner: "Card owner",
    bankCardOwnerPlaceholder: "Name",
    bankSupplier: "Supplier",
    bankBuyPrice: "Buy",
    bankSellPrice: "Sell",
    bankProfitAccount: "Company",
    bankSelectAccount: "Select account",
    bankSelectCountry: "Select currency",
    bankSelectBank: "Select bank",
    bankSelectType: "Select type",
    bankSelectContract: "Select contract",
    bankNameRequired: "Card owner is required",
    bankProfitSharing: "Profit sharing",
    bankSelectedProfitSharing: "Selected profit sharing",
    bankAddProfitSharing: "Add profit sharing",
    bankNoProfitSharing: "No profit sharing selected",
    bankAddAccountRow: "+ Add account",
    bankAddConfirm: "Add",
    bankRemoveRow: "Remove",
    bankProfitSharingHint: "CODE - 10.00, CODE2 - 5.00",
    bankProfitSharingPercentMax100: "Percentage cannot exceed 100%.",
    bankProfitSharingExceedsRemaining: "This amount exceeds the remaining profit ({remaining}). Please enter a smaller amount or percentage.",
    bankInsurance: "Insurance",
    bankSop: "SOP",
    bankSopPlaceholder: "SOP notes…",
    bankMonthlyCap: "Cap day end to monthly billing",
    bankDayEndEarlier: "Day end cannot be earlier than day start",
    bankDayEndRequiredForCap: "Day end is required when monthly cap is on",
    bankContractRequired: "Contract is required for this frequency",
    bankSaveOk: "Process saved",
    bankSaveFailed: "Failed to save process",
    bankLoadFormFailed: "Failed to load process",
    bankDeleteConfirm: "Delete this inactive process? This cannot be undone.",
    bankDeleteOk: "Process deleted",
    bankDeleteFailed: "Failed to delete process",
    bankAddAccountTitle: "Add account",
    bankAccountId: "Account ID",
    bankAccountName: "Name",
    bankAccountRole: "Role",
    bankAccountPassword: "Password",
    bankSelectRole: "Select role",
    bankAccountRequired: "Account ID, name, role and password are required",
    bankAccountCreateFailed: "Failed to create account",
    save: "Save",

    // Scope
    scope: "Scope",
    company: "Company",
    group: "Group",
    selectScope: "Select scope",
    groupAggregate: "Group (all companies)",
    apply: "Apply",
    cancel: "Cancel",

    // Filters
    filter: "Filter",
    dateRange: "Date range",
    dateFrom: "From",
    dateTo: "To",
    category: "Category",
    transactionType: "Transaction type",
    allTypes: "All",
    allProcesses: "All processes",
    keyword: "Keyword",
    searchPlaceholder: "Account, description or remark",
    showResults: "Show results",
    reset: "Reset",
    readOnlyNote: "Transaction Maintenance is read-only.",

    // Card / row labels
    process: "Process",
    product: "Product",
    account: "Account",
    accountTo: "To",
    accountFrom: "From",
    description: "Description",
    remark: "Remark",
    currency: "Currency",
    rate: "Rate",
    amount: "Amount",
    submitter: "By",
    deletedBy: "Deleted by",
    deletedTag: "DELETED",

    // States
    loading: "Loading…",
    noData: "No records found. Adjust filters and try again.",
    loadFailed: "Failed to load records.",
    foundRecords: "Found {n} record(s)",

    // Payment delete
    selectedCount: "{n} selected",
    delete: "Delete",
    deleteRecords: "Delete records",
    deleteConfirmTitle: "Delete {n} payment record(s)?",
    deleteConfirmBody:
      "Deleted records stay visible in payment history. Related RATE entries may also be removed.",
    cannotUndo: "This action cannot be undone.",
    deleteSuccess: "Deleted {n} record(s)",
    deleteFailed: "Delete failed",
    selectAtLeastOne: "Please select at least one record",
    notSelectable: "This row cannot be deleted",
  },
  zh: {
    ...DASHBOARD_I18N.zh,

    maintenance: "维护",
    maintenanceDescription: "交易与支付记录。",
    maintenanceBadge: "维护",

    hubTitle: "维护中心",
    hubSubtitle: "查看业务记录并管理数据。",
    backToHub: "返回维护",
    backToMore: "返回更多",
    sectionRecords: "记录",
    sectionSetup: "设置",
    comingSoon: "即将上线",

    txMaintenanceTitle: "交易维护",
    txMaintenanceDesc: "查看交易与数据采集记录。",
    txFeatures: "审计记录 · 只读 · 筛选",

    payMaintenanceTitle: "支付维护",
    payMaintenanceDesc: "查看并删除支付记录。",
    payFeatures: "支付历史 · 删除记录",
    deleteAccess: "删除权限",

    bpMaintenanceTitle: "银行维护",
    bpMaintenanceDesc: "查看并删除银行流程入账交易。",
    bpFeatures: "银行流程入账 · 批次勾选 · 删除",
    bpSearchPlaceholder: "流程、账户、银行或卡主…",
    bpNeedCompany: "请选择 Bank 公司以加载记录。",
    bpScopeNote: "仅支持公司范围。同一 Post/Resend 批次会一起勾选。",
    bpDeleteConfirmTitle: "删除 {n} 条银行流程记录？",
    bpDeleteConfirmBody: "删除后记录仍会显示在历史中。仅删除由银行流程入账的交易。",

    setupDataCapture: "数据采集",
    setupFormula: "公式",
    setupBank: "银行流程",
    setupBankDesc: "银行流程列表、筛选、状态与表单。",
    setupBankFeatures: "列表 · 状态 · 待入账 · 新增/编辑",
    bankProcessTitle: "银行流程",
    bankSearchPlaceholder: "供应商、银行、卡主…",
    bankStatus: "状态",
    bankShowActive: "启用",
    bankShowInactive: "停用",
    bankShowOfficial: "官方",
    bankShowEInvoice: "电子发票",
    bankShowBlocked: "封锁",
    bankStatusActive: "启用",
    bankStatusInactive: "停用",
    bankStatusOfficial: "官方",
    bankStatusEInvoice: "电子发票",
    bankStatusBlock: "封锁",
    bankAllCurrencies: "全部",
    bankCost: "成本",
    bankPrice: "售价",
    bankProfit: "利润",
    bankNeedCompany: "请选择 Bank 公司以加载流程。",
    bankUnauthorizedCompany: "该公司没有 Bank 类别。请在筛选中切换公司。",
    bankReadOnlyNote: "仅支持公司范围。点 + 新增，或从卡片进入编辑。",
    bankActionsTitle: "流程",
    bankSaveStatus: "保存状态",
    bankRemark: "备注",
    bankRemarkPlaceholder: "填写备注…",
    bankResend: "重送",
    bankResendTitle: "重送到待入账",
    bankProcessLabel: "流程",
    bankDayStart: "开始日",
    bankDayEnd: "结束日",
    bankFrequency: "频率",
    bankFreqFirstOfMonth: "每月1号",
    bankFreqMonthly: "每月",
    bankFreqWeek: "每周",
    bankFreqDay: "每日",
    bankFreqOnce: "一次",
    bankAccountingDue: "待入账",
    bankPostTransaction: "入账",
    bankPost: "入账",
    bankRefresh: "刷新",
    bankRestoreDismissed: "恢复",
    bankNoDue: "暂无待入账项目。",
    bankPostedToday: "今日已入账",
    bankDueAwaiting: "{n} 条待处理",
    bankContract: "合同",
    bankCustomer: "客户",
    bankStatusUpdated: "状态已更新",
    bankStatusFailed: "状态更新失败",
    bankRemarkUpdated: "备注已更新",
    bankRemarkFailed: "备注更新失败",
    bankResendOk: "已重送到待入账",
    bankResendFailed: "重送失败",
    bankPostOk: "已入账",
    bankPostFailed: "入账失败",
    bankDismissOk: "已从待入账移除",
    bankDismissFailed: "移除失败",
    bankAddTitle: "新增流程",
    bankEditTitle: "编辑流程",
    bankEdit: "编辑",
    bankAdd: "新增流程",
    bankFormStepIdentity: "身份",
    bankFormStepMoney: "金额",
    bankFormStepSchedule: "排期",
    bankFormBack: "上一步",
    bankFormNext: "下一步",
    bankSectionBankInfo: "银行信息",
    bankSectionDetail: "明细",
    bankSectionSchedule: "排期",
    bankSectionNotes: "备注",
    bankCountryCurrency: "国家（货币）",
    bankBank: "银行",
    bankType: "类型",
    bankType_PERSONAL: "个人",
    bankType_ENTERPRISE: "企业",
    bankType_BUSINESS: "商务",
    bankCardOwner: "卡主",
    bankCardOwnerPlaceholder: "姓名",
    bankSupplier: "供应商",
    bankBuyPrice: "买入",
    bankSellPrice: "卖出",
    bankProfitAccount: "公司账户",
    bankSelectAccount: "选择账户",
    bankSelectCountry: "选择货币",
    bankSelectBank: "选择银行",
    bankSelectType: "选择类型",
    bankSelectContract: "选择合同",
    bankNameRequired: "请填写卡主",
    bankProfitSharing: "利润分成",
    bankSelectedProfitSharing: "已选利润分成",
    bankAddProfitSharing: "添加利润分成",
    bankNoProfitSharing: "尚未选择利润分成",
    bankAddAccountRow: "+ 添加账户",
    bankAddConfirm: "添加",
    bankRemoveRow: "移除",
    bankProfitSharingHint: "CODE - 10.00, CODE2 - 5.00",
    bankProfitSharingPercentMax100: "百分比不能超过 100%。",
    bankProfitSharingExceedsRemaining: "金额超过剩余利润（{remaining}）。请输入更小的金额或百分比。",
    bankInsurance: "保险",
    bankSop: "SOP",
    bankSopPlaceholder: "SOP 说明…",
    bankMonthlyCap: "按月末封顶日",
    bankDayEndEarlier: "结束日不能早于开始日",
    bankDayEndRequiredForCap: "启用月末封顶时必须填写结束日",
    bankContractRequired: "此频率需要填写合同",
    bankSaveOk: "流程已保存",
    bankSaveFailed: "保存失败",
    bankLoadFormFailed: "加载流程失败",
    bankDeleteConfirm: "删除此停用流程？此操作无法撤销。",
    bankDeleteOk: "流程已删除",
    bankDeleteFailed: "删除失败",
    bankAddAccountTitle: "新增账户",
    bankAccountId: "账户编号",
    bankAccountName: "名称",
    bankAccountRole: "角色",
    bankAccountPassword: "密码",
    bankSelectRole: "选择角色",
    bankAccountRequired: "请填写账户编号、名称、角色与密码",
    bankAccountCreateFailed: "创建账户失败",
    save: "保存",

    scope: "范围",
    company: "公司",
    group: "集团",
    selectScope: "选择范围",
    groupAggregate: "集团（所有公司）",
    apply: "应用",
    cancel: "取消",

    filter: "筛选",
    dateRange: "日期范围",
    dateFrom: "开始",
    dateTo: "结束",
    category: "类别",
    transactionType: "交易类型",
    allTypes: "全部",
    allProcesses: "全部流程",
    keyword: "关键词",
    searchPlaceholder: "账号、说明或备注",
    showResults: "查看结果",
    reset: "重置",
    readOnlyNote: "交易维护为只读页面。",

    process: "流程",
    product: "产品",
    account: "账户",
    accountTo: "入账",
    accountFrom: "出账",
    description: "说明",
    remark: "备注",
    currency: "币种",
    rate: "汇率",
    amount: "金额",
    submitter: "提交",
    deletedBy: "删除人",
    deletedTag: "已删除",

    loading: "加载中…",
    noData: "暂无记录。请调整筛选条件后重试。",
    loadFailed: "加载记录失败。",
    foundRecords: "共找到 {n} 条记录",

    selectedCount: "已选 {n} 条",
    delete: "删除",
    deleteRecords: "删除记录",
    deleteConfirmTitle: "删除 {n} 条支付记录？",
    deleteConfirmBody: "删除后记录仍会显示在支付历史中。关联的 RATE 分录也可能被删除。",
    cannotUndo: "此操作不可撤销。",
    deleteSuccess: "已删除 {n} 条记录",
    deleteFailed: "删除失败",
    selectAtLeastOne: "请至少选择一条记录",
    notSelectable: "该记录不可删除",
  },
};

export const getMaintenanceText = createGetText(MAINTENANCE_I18N);

export function maintenanceText(lang) {
  return MAINTENANCE_I18N[lang] || MAINTENANCE_I18N.en;
}

/** Payment Maintenance transaction types. */
export const PAYMENT_MAINTENANCE_TYPES = [
  "PAYMENT",
  "RECEIVE",
  "CONTRA",
  "CLAIM",
  "RATE",
  "ADJUSTMENT",
];
