import { DASHBOARD_I18N } from "./dashboardTranslate.js";

export const MORE_I18N = {
  en: {
    ...DASHBOARD_I18N.en,
    more: "More",
    moreSubtitle: "Tools and reports",
    report: "Report",
    reportDescription: "View financial and operational reports.",
    userManagement: "User Management",
    userManagementDescription: "Manage users, roles and permissions.",
    domain: "Domain",
    domainDescription: "C168 domain list, fees and renewals.",
    announcement: "Announcement",
    announcementDescription: "Create, edit and delete announcements.",
    autoRenew: "Auto Renew",
    autoRenewDescription: "Approve company and group renewals.",
    noTools: "No additional tools are available for your account.",
    open: "Open",
  },
  zh: {
    ...DASHBOARD_I18N.zh,
    more: "更多",
    moreSubtitle: "工具与报表",
    report: "报表",
    reportDescription: "查看财务与营运报表。",
    userManagement: "用户管理",
    userManagementDescription: "管理用户、角色与权限。",
    domain: "Domain",
    domainDescription: "C168 Domain 列表、费用与续期。",
    announcement: "公告",
    announcementDescription: "创建、编辑与删除公告。",
    autoRenew: "自动续费",
    autoRenewDescription: "审批公司与集团续费申请。",
    noTools: "你的账户暂无其他可用工具。",
    open: "打开",
  },
};
