import { createGetText } from "./i18nHelpers.js";

export const TRANSACTION_I18N = {
  en: {
    transactionList: "Transaction List",
    contraInbox: "Contra Inbox",
    refresh: "Refresh",
    loading: "Loading...",
    date: "Date",
    from: "From",
    to: "To",
    currency: "Currency",
    amount: "Amount",
    submittedBy: "Submitted By",
    description: "Description",
    action: "Action",
    approve: "Approve",
    reject: "Reject",
    close: "Close",
    contraInboxAwaitingApproval: "{count} item awaiting approval",
    contraInboxAwaitingApprovalPlural: "{count} items awaiting approval",
    contraInboxEmpty: "No pending contra transactions for the selected company.",
    contraInboxEmptyHint: "Inbox shows pending approvals from users below Manager. Owner/Manager submissions are auto-approved.",
    confirmRejectContra: "Are you sure you want to reject this Contra transaction? Data will be permanently deleted after rejection.",
    showName: "Show Name",
    showCaptureOnly: "Show Win/Loss Only",
    showPaymentOnly: "Show Payment Only",
    showZeroBalance: "Show all 0 balance",
    category: "Category",
    selectAllCategories: "--Select All--",
    captureDate: "Capture Date",
    groupId: "Group ID:",
    all: "ALL",
    groupFilterAll: "ALL",
    company: "Company:",
    type: "Type",
    placeholderDdMmYyyy: "dd/mm/yyyy",
    transactionDate: "Transaction date",
    account: "Account",
    toAccount: "To Account",
    fromAccount: "From Account",
    selectToAccount: "--Select To Account--",
    selectFromAccount: "--Select From Account--",
    searchAccount: "Search account...",
    reverse: "Reverse",
    reverseAccounts: "Reverse accounts",
    selectCurrency: "--Select Currency--",
    rateTransactionDate: "Rate transaction date",
    rateMultiplier: "Rate multiplier",
    fee: "Fee",
    platformFee: "PT-Fee",
    middleMan: "Middle-Man",
    selectMiddleManAccount: "--Select Account--",
    descriptionField: "Description",
    remark: "Remark",
    confirmSubmit: "Confirm Submit",
    submitting: "Submitting...",
    submit: "Submit",
    search: "Search",
    exitTypeSearchAndRefresh: "Exit type search and refresh",
    exitTypeSearchAndRefreshTitle: "Exit type search and return to the default transaction list",
    pullToExitTypeSearch: "Pull down to exit search and return to the default list",
    loadingData: "Loading data",
    accountTable: "Account",
    accountTableCompact: "Acc",
    nameTable: "Name",
    bfTable: "B/F",
    winLossTable: "Win/Loss",
    crDrTable: "Cr/Dr",
    balanceTable: "Balance",
    total: "Total",
    currencyLabel: "Currency:",
    loadingHistory: "Loading history…",
    exportPdf: "Export PDF",
    exportPdfTitle: "WIN/LOSE REPORT",
    exportPdfTitleWithAccount: "{{account}} - WIN/LOSE REPORT",
    exportPdfHint: "Same as Member Win/Loss table.",
    exportPdfCurrency: "Currency",
    exportPdfDateRange: "Date Range",
    exportPdfSelectDateRange: "Select date range",
    exportPdfSelectEndDate: "Select end date",
    exportPdfPeriod: "Period",
    exportPdfCancel: "Cancel",
    exportPdfExporting: "Exporting…",
    exportPdfFailed: "Export failed",
    exportPdfPopupBlocked: "Please allow pop-ups for this site to export PDF.",
    exportPdfLoadCurrenciesFailed: "Could not load currencies for this account.",
    exportPdfNoCurrencies: "No currencies available for this account.",
    exportPdfMissingAccount: "Account information is missing. Close and reopen Payment History.",
    paymentHistorySubtitle: "Complete transaction history and balance details",
    paymentHistoryShowingEntries: "Showing {count} entries",
    paymentHistoryBalanceHint:
      "Newest first; B/F stays on top. Balance is the running balance after that entry (not reordered).",
    paymentHistoryTapRowHint: "Tap a row to show description and remark",
    paymentHistoryDetails: "Details",
    dateCompact: "Date",
    typeCompact: "Type",
    remarkCompact: "Remark",
    idProduct: "Id Product",
    rate: "Rate",
    createdBy: "CREATER",
    idProductCompact: "Product",
    currencyCompact: "CCY",
    winLossTableCompact: "W/L",
    balanceTableCompact: "Bal.",
    descriptionCompact: "Desc.",
    createdByCompact: "By",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    thisYear: "This Year",
    lastYear: "Last Year",
    toleranceBanner: "Summary Win/Loss tolerance is enabled (<code>tx_wl_tol=1</code>): when absolute total Win/Loss ≤ <strong>RM1.00</strong>, <strong>0.00</strong> will be displayed, and Balance will be recalculated for that row; account columns &amp; API remain accurate.",
    pleaseSelectDateRange: "Please select date range",
    pleaseSelectAtLeastOneCurrency: "Please select at least one Currency or select All",
    searchCompletedNoData: "Search completed but no data found. Please check date range, Currency filter, or confirm data has been submitted",
    searchReturnedRowsNoneMatch: "Search returned {totalAccounts} row(s), but none match current display filters (e.g. zero balance hidden when \"Show 0 balance\" is off, or \"Show Payment Only\" / \"Show Win/Loss Only\"). Enable \"Show 0 balance\" or adjust filters.",
    searchCompletedFoundRecords: "Search completed, found {displayed} record(s)",
    searchFailed: "Search failed",
    searchFailedWithMessage: "Search failed: {message}",
    couldNotResolveAccount: "Could not resolve account for this row",
    synced: "Synced {text}",
    syncedAmount: "Synced Amount: {amount}",
    syncedFromAccount: "From Account: {account}",
    syncedToAccount: "To Account: {account}",
    syncedAmountShort: "Amount: {amount}",
    syncedCurrency: "Currency: {currency}",
    fromAccount: "From",
    toAccount: "To",
    readOnlyModeCannotSubmit: "Read-only mode: cannot submit transactions",
    pleaseSelectTransactionType: "Please select transaction type",
    pleaseSelectToAccount: "Please select To Account",
    profitPleaseSelectFromAccount: "PROFIT: Please select From Account",
    profitSameAccountError: "PROFIT: Select To Account and Select From Account cannot be the same",
    paymentContraEtcNeedFromAccount: "PAYMENT/CONTRA/CLAIM/CLEAR transaction requires From Account",
    receiveTypeDisabled: "RECEIVE transaction type is no longer available",
    pleaseSelectTransactionDate: "Please select transaction date",
    rateTransactionNeedFromAccount: "Rate transaction requires From Account",
    pleaseSelectBothCurrencies: "Please select both currencies",
    pleaseEnterValidCurrencyAmounts: "Please enter valid currency amounts",
    pleaseEnterValidRateValue: "Please enter a valid rate value (supports * and /, max 8 decimal places)",
    pleaseSelectMiddleManAccount: "Please select Middle-Man account",
    pleaseEnterMiddleManRate: "Please enter Middle-Man rate multiplier",
    pleaseEnterMiddleManRateOrFee: "Please enter Middle-Man rate multiplier or Fee",
    middleManRateMaxDecimals: "Middle-Man rate supports max 8 decimal places",
    rateAmountMaxDecimals: "RATE amount supports max 8 decimal places",
    amountMaxDecimals: "Amount supports max 6 decimal places",
    submittedWaitingApproval: "Submitted. Waiting for Manager+ approval to take effect.",
    rateTransactionSubmitted: "RATE transaction submitted successfully",
    transactionSubmitted: "Transaction submitted successfully",
    submitFailed: "Submit failed",
    networkError: "Network error. Please try again.",
    pleaseEnterValidAmount: "Please enter a valid amount",
    pleaseEnterNonZeroAdjustment: "Please enter a non-zero adjustment amount",
    profitEnterNonZeroAmount: "PROFIT: enter a non-zero amount (positive = WIN, negative = LOSE)",
    pleaseEnterValidAmountGteZero: "Please enter a valid amount (>= 0)",
    pleaseSelectCurrency: "Please select Currency",
    monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    weekdaysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    addTransaction: "Add Transaction",
    fabMenu: "Transaction actions",
    fabCloseMenu: "Close menu",
    fabSearchPayment: "Type Search",
    fabAddPayment: "Add Payment",
    searchTypeTitle: "Type Search",
    fabSearchHint: "Choose a type, then Search — same as desktop Type Search (filters accounts).",
    accountList: "Accounts",
    tapForHistory: "Tap for payment history",
    paymentHistory: "Payment History",
    backToList: "Back to list",
    noAccountsFound: "No accounts match current filters",
    leftBalanceTab: "Balance +",
    rightBalanceTab: "Balance -",
    accountSideTabs: "Account balance sides",
    tableClickHint: "Tap account → history · Tap balance → fill form (Balance+→From, Balance-→To)",
    cardClickHint: "Tap account name → history · Tap Bal. → fill form (Balance+→From, Balance-→To)",
    tapBalanceToFill: "Tap balance to fill transaction form",
    tapBalanceAria: "Tap balance {account} {amount} to fill form",
    nextStep: "Next",
    prevStep: "Back",
    rateStep1: "Rate — currencies",
    rateStep2: "Rate — fees & transfer",
    optional: "Optional",
    navTransaction: "Transaction",
  },
  zh: {
    transactionList: "交易列表",
    contraInbox: "抵消收件箱",
    refresh: "刷新",
    loading: "加载中...",
    date: "日期",
    from: "来自",
    to: "至",
    currency: "货币",
    amount: "金额",
    submittedBy: "提交人",
    description: "说明",
    action: "操作",
    approve: "批准",
    reject: "拒绝",
    close: "关闭",
    contraInboxAwaitingApproval: "{count} 条待审批",
    contraInboxAwaitingApprovalPlural: "{count} 条待审批",
    contraInboxEmpty: "当前所选公司暂无待审批的抵消交易。",
    contraInboxEmptyHint: "收件箱显示 Manager 以下用户提交的待审批交易；Owner/Manager 自己提交的交易会自动批准，不会出现在此处。",
    confirmRejectContra: "确定要拒绝这条抵消交易吗？拒绝后数据将被永久删除。",
    showName: "显示名称",
    showCaptureOnly: "仅显示输赢",
    showPaymentOnly: "仅显示支付",
    showZeroBalance: "显示所有0余额",
    category: "类别",
    selectAllCategories: "--全选--",
    captureDate: "捕获日期",
    groupId: "集团：",
    groupFilterAll: "全部",
    all: "ALL",
    company: "公司：",
    type: "类型",
    placeholderDdMmYyyy: "日/月/年",
    transactionDate: "交易日期",
    account: "账户",
    toAccount: "转入账户",
    fromAccount: "转出账户",
    selectToAccount: "--选择转入账户--",
    selectFromAccount: "--选择转出账户--",
    searchAccount: "搜索账号...",
    reverse: "互换",
    reverseAccounts: "互换账户",
    selectCurrency: "--选择货币--",
    rateTransactionDate: "汇率交易日期",
    rateMultiplier: "汇率乘数",
    fee: "手续费",
    platformFee: "平台费",
    middleMan: "中间人",
    selectMiddleManAccount: "--选择账户--",
    descriptionField: "说明",
    remark: "备注",
    confirmSubmit: "确认提交",
    submitting: "提交中...",
    submit: "提交",
    search: "搜索",
    exitTypeSearchAndRefresh: "退出类型搜索并刷新",
    exitTypeSearchAndRefreshTitle: "退出类型搜索并返回默认交易列表",
    pullToExitTypeSearch: "下拉可退出搜索并回到默认列表",
    loadingData: "正在加载数据",
    accountTable: "账户",
    accountTableCompact: "账户",
    nameTable: "名称",
    bfTable: "期初",
    winLossTable: "输赢",
    crDrTable: "借/贷",
    balanceTable: "余额",
    total: "合计",
    currencyLabel: "货币：",
    loadingHistory: "正在加载历史记录…",
    exportPdf: "导出 PDF",
    exportPdfTitle: "WIN/LOSE 报表",
    exportPdfTitleWithAccount: "{{account}} - WIN/LOSE 报表",
    exportPdfHint: "与 Member 页输赢表一致。",
    exportPdfCurrency: "货币",
    exportPdfDateRange: "日期范围",
    exportPdfSelectDateRange: "选择日期范围",
    exportPdfSelectEndDate: "选择结束日期",
    exportPdfPeriod: "快捷区间",
    exportPdfCancel: "取消",
    exportPdfExporting: "导出中…",
    exportPdfFailed: "导出失败",
    exportPdfPopupBlocked: "请允许本站弹出窗口以导出 PDF。",
    exportPdfLoadCurrenciesFailed: "无法加载该账户的货币列表。",
    exportPdfNoCurrencies: "该账户暂无可用货币。",
    exportPdfMissingAccount: "缺少账户信息，请关闭后重新打开 Payment History。",
    paymentHistorySubtitle: "完整交易历史与余额明细",
    paymentHistoryShowingEntries: "共 {count} 条记录",
    paymentHistoryBalanceHint: "最新在上，B/F 固定置顶。余额为该笔发生后的累计余额（不会因排序重算）。",
    paymentHistoryTapRowHint: "点击一行可查看说明与备注",
    paymentHistoryDetails: "详情",
    dateCompact: "日期",
    typeCompact: "类型",
    remarkCompact: "备注",
    idProduct: "产品编号",
    rate: "汇率",
    createdBy: "创建者",
    idProductCompact: "产品",
    currencyCompact: "币种",
    winLossTableCompact: "输赢",
    balanceTableCompact: "余额",
    descriptionCompact: "说明",
    createdByCompact: "创建",
    today: "今天",
    yesterday: "昨天",
    thisWeek: "本周",
    lastWeek: "上周",
    thisMonth: "本月",
    lastMonth: "上月",
    thisYear: "今年",
    lastYear: "去年",
    toleranceBanner: "已启用底部 Summary Win/Loss 展示容差（<code>tx_wl_tol=1</code>）：合计 Win/Loss 绝对值不超过 <strong>RM1.00</strong> 时将显示 <strong>0.00</strong>，并重算该行 Balance；各账户列与 API 仍为真实轧差。",
    pleaseSelectDateRange: "请选择日期范围",
    pleaseSelectAtLeastOneCurrency: "请至少选择一个货币或选择全部",
    searchCompletedNoData: "搜索完成但未找到数据。请检查日期范围、货币筛选，或确认数据已提交",
    searchReturnedRowsNoneMatch: "搜索返回 {totalAccounts} 条记录，但没有符合当前显示筛选条件的记录（例如：未开启「显示0余额」时隐藏了0余额，或开启了「仅显示支付」/「仅显示输赢」）。请开启「显示0余额」或调整筛选条件。",
    searchCompletedFoundRecords: "搜索完成，找到 {displayed} 条记录",
    searchFailed: "搜索失败",
    searchFailedWithMessage: "搜索失败: {message}",
    couldNotResolveAccount: "无法解析此记录的账户",
    synced: "已同步 {text}",
    syncedAmount: "已同步金额: {amount}",
    syncedFromAccount: "从账户: {account}",
    syncedToAccount: "到账户: {account}",
    syncedAmountShort: "金额: {amount}",
    syncedCurrency: "货币: {currency}",
    fromAccount: "从账户",
    toAccount: "到账户",
    readOnlyModeCannotSubmit: "只读模式：无法提交交易",
    pleaseSelectTransactionType: "请选择交易类型",
    pleaseSelectToAccount: "请选择到账户",
    profitPleaseSelectFromAccount: "利润：请选择从账户",
    profitSameAccountError: "利润：选择到账户和选择从账户不能相同",
    paymentContraEtcNeedFromAccount: "支付/抵消/索赔/清算交易需要从账户",
    receiveTypeDisabled: "RECEIVE 交易类型已停用",
    pleaseSelectTransactionDate: "请选择交易日期",
    rateTransactionNeedFromAccount: "汇率交易需要从账户",
    pleaseSelectBothCurrencies: "请选择两种货币",
    pleaseEnterValidCurrencyAmounts: "请输入有效的货币金额",
    pleaseEnterValidRateValue: "请输入有效的汇率值（支持 * 和 /，最多8位小数）",
    pleaseSelectMiddleManAccount: "请选择中间人账户",
    pleaseEnterMiddleManRate: "请输入中间人汇率乘数",
    pleaseEnterMiddleManRateOrFee: "请输入中间人汇率乘数或手续费",
    middleManRateMaxDecimals: "中间人汇率最多支持8位小数",
    rateAmountMaxDecimals: "RATE 金额最多支持8位小数",
    amountMaxDecimals: "金额最多支持6位小数",
    submittedWaitingApproval: "已提交。等待经理以上级别批准后生效。",
    rateTransactionSubmitted: "汇率交易提交成功",
    transactionSubmitted: "交易提交成功",
    submitFailed: "提交失败",
    networkError: "网络错误。请重试。",
    pleaseEnterValidAmount: "请输入有效的金额",
    pleaseEnterNonZeroAdjustment: "请输入非零的调整金额",
    profitEnterNonZeroAmount: "利润：输入非零金额（正数=赢，负数=输）",
    pleaseEnterValidAmountGteZero: "请输入有效的金额（>= 0）",
    pleaseSelectCurrency: "请选择货币",
    monthsShort: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
    weekdaysShort: ["日", "一", "二", "三", "四", "五", "六"],
    addTransaction: "新增交易",
    fabMenu: "交易操作",
    fabCloseMenu: "关闭菜单",
    fabSearchPayment: "类型搜索",
    fabAddPayment: "新增付款",
    searchTypeTitle: "类型搜索",
    fabSearchHint: "选择类型后点搜索——与桌面 Type Search 相同（按类型筛选账户）。",
    accountList: "账户列表",
    tapForHistory: "点击查看支付历史",
    paymentHistory: "支付历史",
    backToList: "返回列表",
    noAccountsFound: "没有符合筛选条件的账户",
    leftBalanceTab: "余额 +",
    rightBalanceTab: "余额 -",
    accountSideTabs: "账户余额左右栏",
    tableClickHint: "点账户 → 历史 · 点余额 → 填表单（余额+→转出，余额-→转入）",
    cardClickHint: "点账户名 → 历史 · 点余额 → 填表单（余额+→转出，余额-→转入）",
    tapBalanceToFill: "点击余额填入交易单",
    tapBalanceAria: "点击余额 {account} {amount} 填入交易单",
    nextStep: "下一步",
    prevStep: "上一步",
    rateStep1: "汇率 — 货币",
    rateStep2: "汇率 — 手续费与转账",
    optional: "可选",
    navTransaction: "交易",
  },
};

export const getTransactionText = createGetText(TRANSACTION_I18N);
